### ISSUE TITLE
Error in frontend markdown

### ISSUE THREAD

**Issue by NMathar** [totaljs/wiki#3]
Hi Peter, 
your wiki app is realy nice but i can't see formated Markdown in Frontend. I get the following error msg

`Error: View "detail": markdown is not defined`

![wiki](https://user-images.githubusercontent.com/8554558/30277094-118f0456-9707-11e7-94dd-adb02667c5d8.png)

 And multiple users would be great but not necessary.

**Comment by petersirka** [comment]
Hi,
I forgot to add `marked` module. Please install `npm install marked` module.

Thank you!
