### ISSUE TITLE
Non-english support in documents naming

### ISSUE THREAD

**Issue by ruslankonev** [totaljs/wiki#7]
Hi guys! Yours Wiki application not support non-english (cyrillic) document naming — routes generate with twice slash `//`

**Comment by petersirka** [comment]
Hi @ruslankonev, yes... but this will work with cyrillic:
https://blog.totaljs.com/blogs/tutorials/20170711-solving-problems-with-utf8-chars-in-slug-method/

**Comment by ruslankonev** [comment]
Thanks Peter!
