### ISSUE TITLE
Adduser

### ISSUE THREAD

**Issue by ghost** [totaljs/wiki#8]
name                          : Wiki
version                       : 1.2.0
author                        : Peter Širka

// A relative URL address into the eshop management
manager-url                   : /$manager
manager-cookie                : __manager

// Super users in the form "name:password"
manager-superadmin  (Array)   : ['admin:admin']
manager-user        (Array)   : ['user:user']

Hello, I cant add a user on the wiki Even a secound superadmin is not possible. Can you help me please?

**Comment by petersirka** [comment]
Hi, it's possible:

```html
manager-superadmin (Array) : ['admin:admin', 'username:password']
```

username + password must be without special chars and spaces.

**Comment by ghost** [comment]
Thank you very much!!!
